services:
  - type: web
    name: url-shortener-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: ADMIN_USERNAME
        value: "bhavin2705"
      - key: USE_POSTGRES
        value: "true"


      - key: DATABASE_URL
        value: "postgresql://postgres.rewgyulmkgijvxnvpcjm:Bhavin%402005%23@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: REDIS_HOST
        value: "epic-gorilla-185314.upstash.io"
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: "gQAAAAAAAtPiAAIgcDI3ZGMzOTcwNjZkZjI0OTA2YTVmNzY2NmE2ZDg1YzJiYQ"




